# Name of the workflow
name: Dev. deploy CI

# Manual trigger
on: workflow_dispatch

concurrency:
  # Unique group name to prevent concurrent runs
  group: stg_deploy_lock
  # Do not cancel a currently running workflow if a new one is triggered
  cancel-in-progress: false

jobs:
  deploy:
    # Only run this job if the workflow is triggered on a release/* branch
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.NEW_NA1149_SSH_KEY }}
          known-hosts: ${{ secrets.NEW_NA119_PPROD_KNOW_HOST }}
          deployer-version: '7.0.0-rc.8'
          dep: deploy pprod
