# Name of the workflow
name: Prod. deploy CI

# Manual trigger
on: workflow_dispatch

concurrency:
  # Unique group name to prevent concurrent runs
  group: prod_deploy_lock
  # Do not cancel a currently running workflow if a new one is triggered
  cancel-in-progress: false

jobs:
  deploy:
    # Only run this job if the workflow is triggered on main branch
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_APP_PROD_PRIVATE_KEY }}
          deployer-version: '7.3.0'
          dep: deploy prod
